tunnel: 986e6745-7dff-4d9b-a89f-1933b0c2274f
credentials-file: /Users/nakamura.shuta/.cloudflared/986e6745-7dff-4d9b-a89f-1933b0c2274f.json

ingress:
  - hostname: cc-anywhere.yourdomain.com  # ここを実際のドメインに変更してください
    service: http://localhost:5000
  - service: http_status:404