tunnel: YOUR-TUNNEL-ID
credentials-file: ~/.cloudflared/YOUR-TUNNEL-ID.json

ingress:
  - hostname: cc-anywhere.yourdomain.com  # ここを実際のドメインに変更してください
    service: http://localhost:5000
  - service: http_status:404